org: danielislas3
app: aws-node-express-dynamodb-api
service: arrenda-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  httpApi:
    cors: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:907457643171:table/contactTable
        - arn:aws:dynamodb:us-west-2:907457643171:table/userTable
functions:
  # Contacts
  - ${file(./yml/Contacts.yml)}
  # Auth
  - ${file(./yml/Auth.yml)}

resources:
  # DynamoDB
  - ${file(./yml/DynamoDB.yml)}
